INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (1, 'Audi')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (2, 'Bugatti')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (3, 'Chevrolet')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (4, 'Honda')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (5, 'Toyota')
